services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dieldatabase
    volumes:
      - pgdata:/data/postgres
    ports:
      - "5432:5432"
    restart: always

volumes:
  pgdata:
    driver: local