services:
  app:
    container_name: testedielback
    build: .
    ports:
      - "3333:3333"
    volumes:
     - .:/usr/app
    depends_on:
      - postgres
    networks:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dieldatabase
    volumes:
      - pgdata:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
  pgdata:
    driver: local